### ISSUE TITLE
Can't get stocks to display at all.

### ISSUE THREAD

**Issue by nazlax10** [alexyak/stocks#12]
I've searched the issues prior to mine and none seem to fix my issue.  This is the response I'm getting from the npm install:

pi@Magic:~ $ cd ~/MagicMirror/modules
pi@Magic:~/MagicMirror/modules $ git clone https://github.com/alexyak/stocks.gitCloning into 'stocks'...
remote: Enumerating objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Unpacking objects: 100% (22/22), done.
pi@Magic:~/MagicMirror/modules $ cd stocks
pi@Magic:~/MagicMirror/modules/stocks $ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

audited 1 package in 2.114s
found 0 vulnerabilities

Am I using the right commands? I copied the module into my config and then used the commands above to install the stocks module folder.

**Comment by djay07** [comment]
same here. I am stuck at the same point, And i also didn't find any good alternative for international stocks.

**Comment by nazlax10** [comment]
I had to remove the .DJI stock code from the module and it worked.
